// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFuZsaF18--Um8SxRSil_2AG6V0m8ov4',
    appId: '1:372675286874:web:d5ad642a494e8deb860563',
    messagingSenderId: '372675286874',
    projectId: 'fir-chat-57e08',
    authDomain: 'fir-chat-57e08.firebaseapp.com',
    storageBucket: 'fir-chat-57e08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHrYsVQc83zu6bK9bQLPu_PKCT4zfyqY',
    appId: '1:372675286874:android:ecbe730e9eda684b860563',
    messagingSenderId: '372675286874',
    projectId: 'fir-chat-57e08',
    storageBucket: 'fir-chat-57e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApngzG7XU9IWn_qkGn22AH-LWYX-9QKgk',
    appId: '1:372675286874:ios:c52864997aceed44860563',
    messagingSenderId: '372675286874',
    projectId: 'fir-chat-57e08',
    storageBucket: 'fir-chat-57e08.appspot.com',
    iosBundleId: 'com.example.firebasechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApngzG7XU9IWn_qkGn22AH-LWYX-9QKgk',
    appId: '1:372675286874:ios:8266d17ea74e5908860563',
    messagingSenderId: '372675286874',
    projectId: 'fir-chat-57e08',
    storageBucket: 'fir-chat-57e08.appspot.com',
    iosBundleId: 'com.example.firebasechat.RunnerTests',
  );
}
